on:
  push:
    tags:
      - 'v*'

name: deploy

jobs:
  deploy_on_github_gist:
    name: Deploy on Github Gist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build WASM Binary
        run: "cd wasm && GOARCH=wasm GOOS=js go build -o testnum.wasm main.go && cd ../"
      - name: Deploy
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: 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
          gist_url: https://gist.github.com/nicolachoquet06250/2f001ee83be8a23e0ec605ec3a9de016
          gist_title: testnum.wasm
          gist_description: build of webassembly-golang repo
          github_file: ./wasm/testnum.wasm
        #uses: exuanbo/actions-deploy-gist@v1
        #with:
        #  token: ${{ secrets.TOKEN }}
        #  gist_id: 2f001ee83be8a23e0ec605ec3a9de016
        #  gist_description: build of webassembly-golang repo
        #  gist_file_name: testnum.wasm
        #  file_path: ./wasm/testnum.wasm