on:
  push:
    tags:
      - 'v*'

name: deploy

jobs:
  deploy_on_github_gist:
    name: Deploy on Github Gist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build WASM Binary
        run: ./wasm/build.sh
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: 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
          gist_id: 2f001ee83be8a23e0ec605ec3a9de016
          gist_description: "build of webassembly-golang repo "
          gist_file_name: testnum.wasm
          file_path: ./wasm/testnum.wasm